# Generated by Django 2.2.12 on 2022-03-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0004_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
