# Generated by Django 4.0.3 on 2022-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_remove_post_disliked_post_disliked_remove_post_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
