# Generated by Django 4.0.3 on 2022-03-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0011_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='postdisliked',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='userdislike',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='dislikevalue',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='postliked',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='userlike',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='likevalue',
            new_name='value',
        ),
    ]
