# Generated by Django 4.0.3 on 2022-03-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0012_rename_postdisliked_dislike_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='value',
            new_name='dislikevalue',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='post',
            new_name='postdisliked',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='user',
            new_name='userdislike',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='value',
            new_name='likevalue',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='postliked',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='userlike',
        ),
    ]
